import type {ReactNode} from 'react';
import type {Metadata} from 'next';
import {AppRouterCacheProvider} from '@mui/material-nextjs/v14-appRouter';

import CssBaseline from '@mui/material/CssBaseline';
import './globals.css';
import {darkTheme, lightTheme} from '@/components/themes/theme';
import ThemeProvider from '@/components/themes/provider';


export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: ReactNode;
}>) {
    return (
        <html lang="en"
              suppressHydrationWarning
              suppressContentEditableWarning
        >
        <body>
        <ThemeProvider >
            {/*<ThemeProvider theme={theme}>*/}
            {/*    <CssBaseline/>*/}
                {children}
            {/*</ThemeProvider>*/}
        </ThemeProvider>
        </body>
        </html>
    );
}
